name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: docker build --build-arg ARCH -t sdk $GITHUB_ACTION_PATH
      shell: bash
    - run: |
        docker run --rm \
          --env BUILD_LOG \
          --env EXTRA_FEEDS \
          --env FEEDNAME \
          --env GITHUB_WORKSPACE \
          --env IGNORE_ERRORS \
          --env PACKAGES \
          --env SIGNED_PACKAGES \
          --env V \
          --workdir /github/workspace \
          -v $(pwd):/github/workspace \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          sdk
      shell: bash
